# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_someobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point2',
            name='title',
        ),
        migrations.AddField(
            model_name='point2',
            name='spatialReference',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
