# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170506_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsGeometryColumns',
            fields=[
                ('view_name', models.TextField(primary_key=True)),
                ('view_geometry', models.TextField(primary_key=True, serialize=False)),
                ('view_rowid', models.TextField()),
                ('f_table_name', models.CharField(max_length=256)),
                ('f_geometry_column', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'views_geometry_columns',
                'managed': False,
            },
        ),
    ]
