# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_point2_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeObject',
        ),
    ]
